### ISSUE TITLE
solr_wrapper/rake_task

### ISSUE THREAD

**Issue by jhriv** [ucsdlib/hyrax-demo#3]
Running the suggested `rake` task
```sh
rake hyrax:default_admin_set:create hyrax:workflow:load
```

resulted in a rake version mismatch between globally installed rake (12.0.0) and the version specified in the Gemfile.lock (12.3.0). Using the rake in the applications's `bin` directory got a little further:

```shellsession
[deploy@lib-d5-smv-2 current]$ pwd
/opt/horton/current
[deploy@lib-d5-smv-2 current]$ bin/rake hyrax:default_admin_set:create hyrax:workflow:load
rake aborted!
LoadError: cannot load such file -- solr_wrapper/rake_task
/opt/horton/releases/20180313214440Z/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/opt/horton/releases/20180313214440Z/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `block in require'
/opt/horton/releases/20180313214440Z/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:258:in `load_dependency'
/opt/horton/releases/20180313214440Z/vendor/bundle/ruby/2.4.0/gems/activesupport-5.1.5/lib/active_support/dependencies.rb:292:in `require'
/opt/horton/releases/20180313214440Z/Rakefile:8:in `<top (required)>'
(See full trace by running task with --trace)
```

The Development Guide was a little less forthcoming about that, so I sought out
[Production Installation Overview](https://github.com/samvera/hyrax/wiki/Production-Installation-Overview) which
> This document was copied from the CC wiki and is outdated.

is also useless.

Being production - we have no need for solr_wrpper; being rake I have no idea how to tell it target:production

**Comment by jhriv** [comment]
Same error (but with more verbosity) when run as `bundle exec rake hyrax:default_admin_set:create hyrax:workflow:load`

**Comment by jhriv** [comment]
Solved.

`env RAILS_ENV=production bundle exec rake hyrax:default_admin_set:create hyrax:workflow:load`
